### ISSUE TITLE
Anybody can access Bus details !

### ISSUE THREAD

**Issue by kamalkoranga** [BT-P1C0/BT-Admin-Website#1]
![image](https://github.com/BT-P1C0/BT-Admin-Website/assets/83089446/01094817-95d1-48c0-a2a8-a9e431539480)

Can we put the data in some kind of database or environment variables?

**Comment by mglsj** [comment]
> ![image](https://user-images.githubusercontent.com/83089446/265500624-01094817-95d1-48c0-a2a8-a9e431539480.png)
> 
> Can we put the data in some kind of database or environment variables?

This info is technically already public.

**Comment by kamalkoranga** [comment]
> > ![image](https://user-images.githubusercontent.com/83089446/265500624-01094817-95d1-48c0-a2a8-a9e431539480.png)
> > 
> > Can we put the data in some kind of database or environment variables?
> 
> This info is technically already public.

Okay :)
